#!/usr/local/bin/php -q
<?php

$pkg_interface = 'console';

require_once("/etc/inc/config.inc");
require_once("/etc/inc/config.lib.inc");
require_once("/etc/inc/util.inc");
require_once("/etc/inc/pfsense-utils.inc");
require_once("/etc/inc/pkg-utils.inc");

// get params
$params = $_GET;
if ( empty($params['pkg']) or empty($params['action']) ) {
  echo "[ERROR] Missing parameters\n";
  exit(1);
}
$pkgid = $params['pkg'];

// validate params
switch ($params['action']) {
  case "install":
    $status = install_package($pkgid);
    if($status == -1) {
      echo "[ERROR] Installation of \"$pkgid\" failed.\n";
      exit(1);
    } else {
      echo "Installation of \"$pkgid\" completed.\n";
      exit;
    }
    break;
  case "deinstall":
    $status = uninstall_package($pkgid);
    if($status == -1) {
      echo "[ERROR] Deinstallation of \"$pkgid\" failed.\n";
      exit(1);
    } else {
      echo "Deinstallation of \"$pkgid\" completed.\n";
      exit;
    }
    break;
  case "info":
    $pkg_info = get_pkg_info(array($pkgid), array("noembedded", "name", "category", "website", "version", "status", "descr", "maintainer", "required_version", "maximum_version", "pkginfolink", "config_file"));
    if($pkg_info) {
      foreach ( $pkg_info[$pkgid] as $key => $value ) {
        echo "$key: $value\n";
      }
      exit;
    } else {
      echo "[ERROR] Package \"$pkgid\" not found.\n";
      exit(1);
    }
    break;
  case "latest":  
    $pkg = ($pkgid == 'all' ? 'all' : array($pkgid));
    $pkg_info = get_pkg_info($pkg, array("name", "version"));
    if($pkg_info) {
      foreach ( $pkg_info as $key => $value ) {
        echo "$key:" . $value['version'] . "\n";
      }
      exit; 
    } else {
      echo "[ERROR] Unable to get version information.\n";
      exit(1);
    }
    break;
  default:
    echo "[ERROR] Invalid action specified\n";
    exit(1);
}

exit;
?>
